### FINAL FANTASY ###

require 'start_screen'

class Game
  
  def initialize(start)
    @start = start
    puts "in init @start = " + @start.inspect
  end

  def prompt()
    print "\nPress Enter to continue."
    @continue = gets.chomp()
    if @continue != "exit"
      print "\nFF7>> ===================================================================================\n\n"
    else
      Process.exit(0)
    end
  end

  def play()
    puts "@start => " + @start.inspect
    next_room = @start

    while true
      puts <<-LOGO



FINAL FANTASY VII
....... .................7..................................
..........................7......................... ..
...... ....................7Z.............................. ......
........................7...78O..................... ........
.........................+?..$ZO.................... .........
+$Z..................++7I=:.7~7O77.................. ..
.DDO7I:................+,,,.+I7O.ZO................. ....
.....D8OZZONOZ8O.... =.~7,+7I8DIO$DZ.. ......
........ZDDDNNN8O...~:$?=$8I$7:,+78Z............
..........8NNNDDN,. +=OZZ$$~$I:$$D8.I............
..........ZDNNNDNOIZI?88ZOO=,:Z=+D.............
..........?=ONDZ..DO$8D8ZZ+D,,++$ND8$..~..7......... ...
..........8ODNDD..888NDOO+,8ONZNNNDZOD8.,.8.........
... .. . ..DDDN8.D8DND8$8$NZ7$ODDDD$N8OZ$Z8DDZ.......
...........Z8DDD:8DMD?+OOONO7$N$$8DO88O88DDDNZ7~.... ....
...... . ..Z:=I7..Z,~=$DZD$7ODDNDDNNZOO8NNNNNN$II77.....
.............~~+?,,~+$OODOZ7$88NDNN88N87I$DDNN$7$7$I .I=I...........
............,.:::::~7.$DN$ZZ8D8NNNNDDN7~~+7DDDD87$$$ I?~.... 
.............:===7... ODNNDNDDDNDDNDDNN=:~~+DNDOZZZ877+=:....7.........
......................8N$8INONNNNDDDNNDD8+~::8OZZZZO OZZ$?~,~~~=+I?. ..
.... ................ 7Z?O87NNNNNN....888D:~+ZO$Z$ZZZZ$ZOOZ+?+?II7$$O. .........
.... ... ........... .=$IOO8NNNNNN.. . ..:?:IZ8NDZ$ZZZZZOZ$$OOZO7$$$Z$..........
.......................IN8ZOO8DNDD: .... ..7I8IODO8$77$Z$$8777$$ZO$ZOZ8.........
......................7$ZZN8O8O8DND,.. ..+,D$D8D.DOZ?$Z?77$$$7$$O$OOZZO8........
..................... DZZDDDD8ZNNDD8...... ~D$I8....?7I$77$ZOZ$$$$I8DD88D ......
......................$888DDODZ88NNND.....:~==88D... ....8II77ZZ8$7OO8DDODO..
......................?I$ODNDDDOO8DDD. ....NNDDN...........,I77$$$$OO88N888.....
. ....................8$$ONNNZZNN888DD....Z888DN...... ....... .$$7OZZ8D8DDOZ
..... ................8D$ODNDI$NNNDDDD8. 8$8DDDD..... ....... ....~OZO8888NO~...
......................NO$ODNN7ZNNNNN8DDN.=NZDN8O.... ................ 88DD88O...
..................... 8D$$NND7$DNDNDDDDN+,?NDN~ ....................... .~OO8O..
.....................DD$$8DN7ZDNDNDD8DDD. ............................. .....DD.
.......... ....... ...DNZZDDNOZDDDDDDDDD8D.. . ..... . ..... . ..... . ..... . 
.....................?8DD$DDNN8DDDDNDD8DD8D... . ..... . ..... . ..... . ..... .
.....................DZ$ZODDDNODDDDDDDDDD8DD........ ...
.....................D$$ZZODDNONDNNDD8DD8DD8O....... .....
.....................7$$$ZZNDNNDNNNND8NOODD8D....... ........
....................DI$ZO$DDDNNNDNDDDODOO8DDD....... ..
....................D$ODI$O8DNNNNNNDNN888NND7....... ....
.....................ND7IZODDNDDND$ZNNDNDO8DD....... ....
..................... D?IZ8DDNND8.?7Z8ND8888DD ....... 
......................I7$ZD88NDD,.D7$ZON8ODDDD...... .........
.......................DZ$Z88NDN8...DDDDN8888D. ............
.......................7I$NONNDNN....Z$OD88DDN...... ...
.......................8I7$ZD8NND....I?$ONNNNN,..... ........
.........................?IDDDDN... .8?7ZONNNND.................................
FINAL FANTASY VII

LOGO
      room = method(next_room)
      next_room = room.call()
    end
  end

  def start_screen()
    puts "NEW GAME"
    puts "Continue?"
    puts "\nPlease Type \"New Game\" or \"Continue\".\n\n"
    print "FF7>> "
    @action = gets.chomp()

    if @action == "New Game"
      return :new_game
    elsif @action == "Continue"
      return :continue
    elsif @action == "exit"
      Process.exit(0)
    else
      puts "クエッ！"
      return :start_screen
    end
  end

  def new_game()
    puts <<-SCENE1
The camera pans slowly across a starfield for
several seconds before you see a beautiful young woman looking directly
at you. Green embers waft upwards around her face. The camera moves to show
that the embers are generated by a Mako furnace in a dark alley as the
woman stares into it. after a few moments, she turns and leaves the alley,
a basket of flowers on one arm, and stops to stand at a street corner.
Your view of her is momentarily obstructed by a massive train as it
speeds past through the town square. The camera swings outward through
the dark, dingy square, under a stone arch, and then begins to swing
upwards. The view moves higher and higher until the entire circular city
of Midgar comes into view. The camera swings back down into a different part
of a city. A train is pulling into a station in another dark alley. Two
guards patrol the platform. Jessie flips spectacularly off the train. The
guards attack the intruder only to be knocked out by her skillfull hands
and feet. Barret hops out of the train, turns, and motions for another
to follow.

Barret >> C'mon newcomer. Follow me.
SCENE1
prompt
puts <<-SCENE1
He runs upstairs. Cloud flips out of the train and follows
him. Two guards come down the stairs down to the train
platform, blocking his path.

Cloud beats the two guards.

After the battle, Cloud runs up the stairs and meets the
group - Jessie, Biggs, and Wedge, opening the main gate
to a Mako reactor.

Biggs >> Wow! You used to be in SOLDIER all right! ...Not
         everyday ya find one in a group like AVALANCHE.
SCENE1
prompt
puts <<-SCENE1
Jessie >> SOLDIER? Aren't they the enemy?
          What's he doing with us in AVALANCHE?
SCENE1
prompt
puts <<-SCENE1
Biggs >> Hold it, Jessie. He WAS in SOLDIER.
         He quit them and now is one of us.
         Didn't catch your name...
SCENE1
prompt
puts <<-SCENE1
Cloud >> ...Cloud.
SCENE1
prompt
puts <<-SCENE1
Biggs >> Cloud, eh? I'm...
SCENE1
prompt
puts <<-SCENE1
Cloud >> I don't care what your names are. Once this job's over... I'm
         outta here.
SCENE1
prompt
puts <<-SCENE1
Barret comes running up from offscreen

Barret >> The hell you all doin'!? I thought I told you never to move in a
           group!
SCENE1
prompt
puts <<-SCENE1
The group heads through the gate. Barret stops and turns to face Cloud.

Barret >> Ex-SOLDIER, huh? Don't trust ya!
SCENE1
prompt
puts <<-SCENE1
The camera swings to show the Shinra headquarter towering
above as Cloud following Barret through the gate.
Cloud follows the others to the Reactor. Wedge stays on the bridge
in front of the reactor as the others head inside.

Wedge >> I'll secure the escape passage. Concentrate on the mission, Cloud.
         Geez, we're really gonna blow this huge furnace up? This'll be
         somethin' to see!
SCENE1
prompt
puts <<-SCENE1
Cloud follows the others into the Reactor

Barret >> Yo! This your first time in a reactor?
SCENE1
prompt
puts <<-SCENE1
Cloud >> No. After all, I did work for Shinra, y'know.
SCENE1
prompt
puts <<-SCENE1
Barret >> The planet's full of Mako energy. People here use it
          every day. It's the life blood of the planet. But Shinra
          keeps suckin' the blood out with these machines.
SCENE1
prompt
puts <<-SCENE1
Cloud >> I'm not here for a lecture. Let's just hurry.
SCENE1
prompt
puts <<-SCENE1
Barret >> That's it! You're comin' with me from now on.
SCENE1
prompt
puts <<-SCENE1
Barret joins Cloud. The group works through the locked doors deeper
inside the reactor.

SCENE1

    Process.exit(0)
  end

  def continue()
    puts "Save functionality soon to come..."
    #puts "Please select save state."
    Process.exit(0)
  end

  #ROOMS = {
  #  :start => method(:start),
  #  :new_game => method(:new_game),
  #  :continue => method(:continue)
  #}

  #def runner(map, start)
  #  next_one = start

  #  while true
  #    room = map[next_one]
  #    puts "\n=======================\n"
  #    next_one = room.call()
  #  end
  #end

  #runner(ROOMS, :start)
  #
end

a_game = Game.new(:start_screen)
a_game.play()
