### FINAL FANTASY ###

require 'start_screen'
puts "start_screen required"

class Game < StartScreen
  
  def initialize(start)
    @start = start
    puts "in init @start = " + @start.inspect
  end

  def play()
    puts "@start => " + @start.inspect
    next_room = @start

    while true
      puts <<-LOGO



FINAL FANTASY VII
....... .................7..................................
..........................7......................... ..
...... ....................7Z.............................. ......
........................7...78O..................... ........
.........................+?..$ZO.................... .........
+$Z..................++7I=:.7~7O77.................. ..
.DDO7I:................+,,,.+I7O.ZO................. ....
.....D8OZZONOZ8O.... =.~7,+7I8DIO$DZ.. ......
........ZDDDNNN8O...~:$?=$8I$7:,+78Z............
..........8NNNDDN,. +=OZZ$$~$I:$$D8.I............
..........ZDNNNDNOIZI?88ZOO=,:Z=+D.............
..........?=ONDZ..DO$8D8ZZ+D,,++$ND8$..~..7......... ...
..........8ODNDD..888NDOO+,8ONZNNNDZOD8.,.8.........
... .. . ..DDDN8.D8DND8$8$NZ7$ODDDD$N8OZ$Z8DDZ.......
...........Z8DDD:8DMD?+OOONO7$N$$8DO88O88DDDNZ7~.... ....
...... . ..Z:=I7..Z,~=$DZD$7ODDNDDNNZOO8NNNNNN$II77.....
.............~~+?,,~+$OODOZ7$88NDNN88N87I$DDNN$7$7$I .I=I...........
............,.:::::~7.$DN$ZZ8D8NNNNDDN7~~+7DDDD87$$$ I?~.... 
.............:===7... ODNNDNDDDNDDNDDNN=:~~+DNDOZZZ877+=:....7.........
......................8N$8INONNNNDDDNNDD8+~::8OZZZZO OZZ$?~,~~~=+I?. ..
.... ................ 7Z?O87NNNNNN....888D:~+ZO$Z$ZZZZ$ZOOZ+?+?II7$$O. .........
.... ... ........... .=$IOO8NNNNNN.. . ..:?:IZ8NDZ$ZZZZZOZ$$OOZO7$$$Z$..........
.......................IN8ZOO8DNDD: .... ..7I8IODO8$77$Z$$8777$$ZO$ZOZ8.........
......................7$ZZN8O8O8DND,.. ..+,D$D8D.DOZ?$Z?77$$$7$$O$OOZZO8........
..................... DZZDDDD8ZNNDD8...... ~D$I8....?7I$77$ZOZ$$$$I8DD88D ......
......................$888DDODZ88NNND.....:~==88D... ....8II77ZZ8$7OO8DDODO..
......................?I$ODNDDDOO8DDD. ....NNDDN...........,I77$$$$OO88N888.....
. ....................8$$ONNNZZNN888DD....Z888DN...... ....... .$$7OZZ8D8DDOZ
..... ................8D$ODNDI$NNNDDDD8. 8$8DDDD..... ....... ....~OZO8888NO~...
......................NO$ODNN7ZNNNNN8DDN.=NZDN8O.... ................ 88DD88O...
..................... 8D$$NND7$DNDNDDDDN+,?NDN~ ....................... .~OO8O..
.....................DD$$8DN7ZDNDNDD8DDD. ............................. .....DD.
.......... ....... ...DNZZDDNOZDDDDDDDDD8D.. . ..... . ..... . ..... . ..... . 
.....................?8DD$DDNN8DDDDNDD8DD8D... . ..... . ..... . ..... . ..... .
.....................DZ$ZODDDNODDDDDDDDDD8DD........ ...
.....................D$$ZZODDNONDNNDD8DD8DD8O....... .....
.....................7$$$ZZNDNNDNNNND8NOODD8D....... ........
....................DI$ZO$DDDNNNDNDDDODOO8DDD....... ..
....................D$ODI$O8DNNNNNNDNN888NND7....... ....
.....................ND7IZODDNDDND$ZNNDNDO8DD....... ....
..................... D?IZ8DDNND8.?7Z8ND8888DD ....... 
......................I7$ZD88NDD,.D7$ZON8ODDDD...... .........
.......................DZ$Z88NDN8...DDDDN8888D. ............
.......................7I$NONNDNN....Z$OD88DDN...... ...
.......................8I7$ZD8NND....I?$ONNNNN,..... ........
.........................?IDDDDN... .8?7ZONNNND.................................
FINAL FANTASY VII

LOGO
      room = method(next_room)
      next_room = room.call()
    end
  end

end

a_game = Game.new(:start_game)
a_game.play()
