### FINAL FANTASY ###

# Start Screen
class StartScreen

  def prompt()
    print "\nPress Enter to continue."
    @continue = gets.chomp()
    if @continue != "exit"
      print "\nFF7>> ===================================================================================\n\n"
    else
      Process.exit(0)
    end
  end

  
    def start_game()
    puts "NEW GAME"
    puts "Continue?"
    puts "\nPlease Type \"New Game\" or \"Continue\".\n\n"
    print "FF7>> "
    @action = gets.chomp()

    if @action == "New Game"
      return :scene1
    elsif @action == "Continue"
      return :continue
    elsif @action == "exit"
      Process.exit(0)
    else
      puts "クエッ！"
      return :start_screen
    end
  end

  def scene1()
    puts <<-TEXT
Scene 1
- Presentiment - AVALANCHE -

The camera pans slowly across a starfield for
several seconds before you see a beautiful young woman looking directly
at you. Green embers waft upwards around her face. The camera moves to show
that the embers are generated by a Mako furnace in a dark alley as the
woman stares into it. after a few moments, she turns and leaves the alley,
a basket of flowers in one arm, and stops to stand at a street corner.
You get momentary flashes of a massive train as it
speeds past through the town square. The camera swings outward through
the dark, dingy square, under a stone arch, and then begins to swing
upwards. The view moves higher and higher until the entire circular city
of Midgar comes into view. The camera swings back down into a different part
of the city. A train is pulling into a station in another dark alley. Two
guards patrol the platform. Jessie flips spectacularly off the train. The
guards attack the intruder only to be knocked out by her skillfull hands
and feet. Barret hops out of the train, turns, and motions for another
to follow.

Barret >> C'mon newcomer. Follow me.
TEXT
  prompt
  puts <<-TEXT
He runs upstairs. You flip out of the train and follow
him. Two guards come down the stairs down to the train
platform, blocking your path.

You beat up both guards.

After the battle, you run up the stairs and meet the
group - Jessie, Biggs, and Wedge, who are opening the main gate
to the Mako reactor.

Biggs >> Wow! You used to be in SOLDIER all right! ...Not
         everyday ya find one in a group like AVALANCHE.
TEXT
  prompt
  puts <<-TEXT
Jessie >> SOLDIER? Aren't they the enemy?
          What's he doing with us in AVALANCHE?
TEXT
  prompt
  puts <<-TEXT
Biggs >> Hold it, Jessie. He WAS in SOLDIER.
         He quit them and now is one of us.
         Didn't catch your name...
TEXT
  prompt

  puts "FF7>> Please type your name. (Default is Cloud)"
  print "FF7>> "
  name = gets.chomp()

  if name == ""
    @name = "Cloud"
  else
    @name = name
  end

  puts "#{@name} >> ...#{@name}."
  prompt
  puts "Biggs >> #{@name}, eh? I'm..."
  prompt
  puts <<-TEXT
#{@name} >> I don't care what your names are. Once this job's over... I'm
         outta here.
TEXT
  prompt
  puts <<-TEXT
Barret comes running up from offscreen

Barret >> The hell you all doin'!? I thought I told you never to move in a
          group!
TEXT
  prompt
  puts <<-TEXT
The group heads through the gate. Barret stops and turns to face you.

Barret >> Ex-SOLDIER, huh? Don't trust ya!
TEXT
  prompt
  puts <<-TEXT
The camera swings to show the Shinra headquarter towering
above as you follow Barret through the gate.
You follow the others to the Reactor. Wedge stays on the bridge
in front of the reactor as the others head inside.

Wedge >> I'll secure the escape passage. Concentrate on the mission, #{@name}.
         Geez, we're really gonna blow this huge furnace up? This'll be
         somethin' to see!
TEXT
  prompt
  puts <<-TEXT
You follow the others into the Reactor.
Barret >> Yo! This your first time in a reactor?
TEXT
  prompt
  puts <<-TEXT
#{@name} >> No. After all, I did work for Shinra, y'know.
TEXT
  prompt
  puts <<-TEXT
Barret >> The planet's full of Mako energy. People here use it
          every day. It's the life blood of the planet. But Shinra
          keeps suckin' the blood out with these machines.
TEXT
  prompt
  puts <<-TEXT
#{@name} >> I'm not here for a lecture. Let's just hurry.
TEXT
  prompt
  puts <<-TEXT
Barret >> That's it! You're comin' with me from now on.
TEXT
  prompt
  puts <<-TEXT
Barret joins your party. The group works through the locked doors deeper
inside the reactor.

Jessie >> Biggs and I got the code for this door.
TEXT
  prompt
  puts <<-TEXT
Biggs >> Code deciphered
TEXT
  prompt
  puts <<-TEXT
You all go through the door.
Biggs >> Think how many of our people risked their lives, just for this
         code...
TEXT
  prompt
  puts <<-TEXT
Jessie >> Code deciphered
TEXT
  prompt
  puts <<-TEXT
You go through the door and work deeper into the reactor. Biggs stays at
the door. You enter the elevator.

Jessie >> Push that button over there!
TEXT
  prompt
  puts <<-TEXT
You press the button. The elevator starts moving.

Barret >> Little by little the reactors'll drain out all the life. And
          that'll be that.
TEXT
  prompt
  puts <<-TEXT
#{@name} >> It's not my problem.
TEXT
  prompt
  puts <<-TEXT
Barret >> The planet's dyin', #{@name}!
TEXT
  prompt
  puts <<-TEXT
#{@name} >> The only thing I care about is finishin' this job before
         security and the Roboguards come.
TEXT
  prompt
  puts <<-TEXT
Barret turns away, shaking with anger, then looks back over his shoulder
at you and rejoins your party. The elevator stops and
Jessie gets off. You continue into the reactor.

Jessie stays behind. You continue to the reactor core.

Barret >> When we blow this place, this ain't gonna be nothin' more
          than a hunka junk. #{@name}, set the bomb.
TEXT
  prompt
  puts <<-TEXT
#{@name} >> Shouldn't you do it?
TEXT
  prompt
  puts <<-TEXT
Barret >> Jus' do it! I gotta watch to make sure you don't pull nothin'.
TEXT
  prompt
  puts <<-TEXT
#{@name} >> Fine, be my guest.
TEXT
  prompt
  puts <<-TEXT
As you move to set the bomb, the screen dims and something speaks into
your mind.

  >> Watch out!
  >> This isn't just a reactor!!

It stops abruptly.

Barret >> ...What's wrong?
TEXT
  prompt
  puts "#{@name} >> Huh?"
  prompt
  puts "Barret >> What's wrong, #{@name}? Hurry it up!"
  prompt
  puts "#{@name} >> Yeah, sorry."
  prompt
  puts <<-TEXT
You set the bomb. An alarm begins to sound and red lights
flash.

Barret >> Heads up, here they come!
TEXT
  prompt
  puts <<-TEXT
You and Barret defeat the Guard Scorpion Boss.

#{@name} >> Come on, let's get outta here!
         Ten minutes to detonation!
TEXT
  prompt
  puts <<-TEXT
You rush back out through the reactor until you meet up with Jessie
where she had stayed behind. She has one leg caught in the grate she's
standing on.

#{@name} >> You all right?
TEXT
  prompt
  puts "Jessie >> My leg got stuck."
  prompt
  puts <<-TEXT
You pull her out.

Jessie >> Thanks!
TEXT
  prompt
  puts <<-TEXT
You go through the door.
Jessie >> Alright, be careful.
TEXT
  prompt
  puts "Biggs >> Code deciphered"
  prompt
  puts <<-TEXT
You go through the door and exit the reactor. On the way out, Jessie
falls. You help her up and spring away. The reactor emits a ring
of fire as it explodes spectacularly against the night sky.
TEXT

  puts "\nEND OF SCENE 1\n"
  puts "SAVE BEFORE MOVING TO SCENE 2?"
  #return :scene2
  end

  def continue()
    puts "Save functionality soon to come..."
    #puts "Please select save state."
    Process.exit(0)
  end

  def scene2()
    puts "This is Scene 2"
    puts "I need to find a way to put this in its own class
    and have this file link to that other class' method."
  end

end
